In [1]:
import torch
import numpy as np


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5318, 0.8505],
        [0.1256, 0.2632]]) 



In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
shape = (2,3,)


In [7]:
shape

(2, 3)

In [8]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


In [9]:
rand_tensor

tensor([[0.8845, 0.8939, 0.6180],
        [0.2574, 0.8394, 0.0450]])

In [10]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
tensor = torch.rand(3,4)


In [13]:
print(tensor.dtype)


torch.float32


In [14]:
if torch.cuda.is_available():
    tensor = torch.to('cuda')


In [15]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
print(f"tensor.mul(tensor) : \n {tensor.mul(tensor)} \n")
    
print(f"tensor*tensor : \n {tensor * tensor} \n")


tensor.mul(tensor) : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor*tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [20]:

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.t)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")


TypeError: matmul(): argument 'other' (position 1) must be Tensor, not builtin_function_or_method

In [22]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [23]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [24]:
t.add_(1)
print(f"t: {t} ")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.]) 
n: [2. 2. 2. 2. 2.]


In [25]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [26]:
t

tensor([2., 2., 2., 2., 2.])

In [27]:
n = np.ones(5)
t = torch.from_numpy(n)

In [28]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
