In [1]:
import torch
import numpy as np


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8627, 0.4992],
        [0.1448, 0.6789]]) 



In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
shape = (2,3,)


In [7]:
shape

(2, 3)

In [8]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


In [9]:
rand_tensor

tensor([[0.8563, 0.1540, 0.2293],
        [0.1508, 0.4351, 0.2718]])

In [10]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
tensor = torch.rand(3,4)


In [13]:
print(tensor.dtype)


torch.float32


In [14]:
if torch.cuda.is_available():
    tensor = torch.to('cuda')


In [15]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [21]:
print(f"tensor.mul(tensor) : \n {tensor.mul(tensor)} \n")
    
print(f"tensor*tensor : \n {tensor * tensor} \n")


tensor.mul(tensor) : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor*tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

