In [1]:
import torch
import numpy as np


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7857, 0.7929],
        [0.0638, 0.5775]]) 



In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
shape = (2,3,)


In [7]:
shape

(2, 3)

In [8]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


In [9]:
rand_tensor

tensor([[0.3551, 0.8905, 0.0366],
        [0.3987, 0.6539, 0.6703]])

In [10]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
tensor = torch.rand(3,4)


In [ ]:
print(tensor.dtype)
