In [23]:
import torch, torchvision


In [24]:
model = torchvision.models.resnet18(pretrained=True)

In [25]:
data = torch.rand(1,3, 64, 64)
labels = torch.rand(1,1000)

In [26]:
data.shape

torch.Size([1, 3, 64, 64])

In [27]:
prediction = model(data)

In [28]:
prediction.shape

torch.Size([1, 1000])

In [29]:
labels.shape

torch.Size([1, 1000])

In [30]:
loss = (prediction -labels).sum()

In [31]:
loss.backward()

In [32]:
loss

tensor(-490.8144, grad_fn=<SumBackward0>)

In [33]:
optim = torch.optim.SGD(model.parameters(),
                        lr=1e-2, 
                        momentum=0.9)

In [34]:
optim.step()

In [35]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [36]:
a

tensor([2., 3.], requires_grad=True)

In [37]:
Q = 3*a**3 - b**2

In [38]:
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

In [39]:
a.grad

tensor([36., 81.])

In [40]:
x = torch.rand(5,5)
y = torch.rand(5,5)
z = torch.rand((5,5),requires_grad=True)

In [41]:
x

tensor([[0.9885, 0.5790, 0.3417, 0.5478, 0.5549],
        [0.5299, 0.1415, 0.3129, 0.5455, 0.9715],
        [0.8961, 0.9010, 0.0052, 0.3574, 0.1656],
        [0.4370, 0.4499, 0.3503, 0.8488, 0.9339],
        [0.7600, 0.6457, 0.9085, 0.3858, 0.7213]])

In [42]:
a = x + y

In [43]:
print(f"Does 'a' require gradients? : {a.requires_grad}")

Does 'a' require gradients? : False


In [44]:
from torch import nn, optim

for param in model.parameters():
    param.requires_grad=False

In [46]:
model.fc = nn.Linear(512, 10)

model.fc

In [48]:
model.fc

Linear(in_features=512, out_features=10, bias=True)