In [1]:
import torch, torchvision


In [2]:
model = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/ma/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|██████████| 44.7M/44.7M [00:02<00:00, 20.3MB/s]


In [3]:
data = torch.rand(1,3, 64, 64)
labels = torch.rand(1,1000)

In [6]:
data.shape

torch.Size([1, 3, 64, 64])

In [7]:
prediction = model(data)

In [9]:
prediction.shape

torch.Size([1, 1000])

In [10]:
labels.shape

torch.Size([1, 1000])

In [11]:
loss = (prediction -labels).sum()

In [12]:
loss.backward()

In [13]:
loss

tensor(-507.1575, grad_fn=<SumBackward0>)

In [14]:
optim = torch.optim.SGD(model.parameters(),
                        lr=1e-2, 
                        momentum=0.9)

In [15]:
optim.step()

In [17]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [18]:
a

tensor([2., 3.], requires_grad=True)

In [19]:
Q = 3*a**3 - b**2

In [23]:
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [21]:
a.grad

tensor([36., 81.])

In [25]:
x = torch.rand(5,5)
y = torch.rand(5,5)
z = torch.rand((5,5),requires_grad=True)

In [26]:
x

tensor([[0.7761, 0.6202, 0.3402, 0.1350, 0.2158],
        [0.1205, 0.8750, 0.0737, 0.0068, 0.0885],
        [0.7287, 0.4827, 0.0048, 0.1980, 0.2219],
        [0.6961, 0.4435, 0.4335, 0.5569, 0.5737],
        [0.0236, 0.5646, 0.0222, 0.0017, 0.7091]])

In [27]:
a = x + y

In [28]:
print(f"Does 'a' require gradients? : {a.requires_grad}")

Does 'a' require gradients? : False


In [29]:
from torch import nn, optim

for param in model.parameters():
    param.requires_grad=False